### PR TITLE
fix: handle relative tsconfig.json paths

### LINKED ISSUE #79: paths matcher in version 4.7.5 resolves incorrect paths
### Problem

paths matcher in version 4.7.5 resolves incorrect paths

steps to reproduce:
- `git clone https://github.com/stefanprobst/issue-get-tsconfig && cd issue-get-tsconfig && pnpm install`
- `node index.mjs`
- see a paths ending in "e2e/e2e/src/check.ts" being logged (note the duplicated "e2e")

to see the behavior in previous version 4.7.3, check out branch "previous-version":
- `git checkout previous-version && pnpm install`
- `node index.mjs`
- see a path ending in "e2e/src/check.ts" being logged

### Expected behavior

paths should resolve correctly (like in v4.7.3)

### Minimal reproduction URL

https://github.com/stefanprobst/issue-get-tsconfig

### Version

4.7.5

### Node.js version

20.15.0

### Package manager

pnpm

### Operating system

Linux

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

### PR DESCRIPTION
**Pull request by stefanprobst**
this fixes a regression introduced in 4.7.3:

previously, the implicit base url used an absolute path (see [here](https://github.com/privatenumber/get-tsconfig/blob/d1c46c04f200a8239f3e5734c42011de1ea11380/src/parse-tsconfig/index.ts#L108)), which was changed to just using `path.dirname()` (see [here](https://github.com/privatenumber/get-tsconfig/blob/0a3270e67ddf9a10b907eb5115f13a56857261ff/src/parse-tsconfig/index.ts#L105))

this resulted in different paths being resolved for the base url [here](https://github.com/privatenumber/get-tsconfig/blob/0a3270e67ddf9a10b907eb5115f13a56857261ff/src/paths-matcher/index.ts#L57) - in the example from #79 this would be:

```ts
// v4.7.5
const resolvedBaseUrl = path.resolve(
  path.dirname("e2e/tsconfig.json"),
  "e2e",
);
// '/home/stefan/e2e/e2e'

// v4.7.3
const resolvedBaseUrl = path.resolve(
  path.dirname("e2e/tsconfig.json"),
  "/home/stefan/e2e",
);
// '/home/stefan/e2e'
```

closes #79

### CODE REVIEW

**Comment by stefanprobst** [comment]
@privatenumber could you take a look at this please? thanks!

**Comment by privatenumber** [comment]
Actually took a look at the time and I was going to add a test but I went down a rabbit hole. Basically this needs a test to land. I don't mind doing it but might take some time.

**Comment by stefanprobst** [comment]
tried adding a test - let me know what you think (it does fail on `master` but passes on this branch).

**Comment by privatenumber** [comment]
Appreciate the PR @stefanprobst Thanks for working on this 🙏

**Pull request merged**
