### PR TITLE
fix: use require.resolve to find package's path

### LINKED ISSUE #26: Resolve error: File not found when using yarn PnP linker
We have this extends in our tsconfig.json
```
"extends": "@equisoft/typescript-config/tsconfig.standards.json"
```

I took a look at #21 and it seems the `resolveExtends` expects the extend to be in `node_modules`.

Discovered this issue while trying to update to eslint-import-resolver-typescript@v3 which uses this library.

### PR DESCRIPTION
**Pull request by meriouma**
Fix #26

### CODE REVIEW

**Comment by privatenumber** [comment]
Thanks for the PR.

Few points:
- We can't use `require.resolve` because it behaves differently form the Tsconfig resolver. It was previously used but [removed here](https://github.com/privatenumber/get-tsconfig/pull/9/files#diff-d76599a488c9e92b509597fb3379a16f4d1dff75ed377168125e20b2297b25e3L29).

    See the tests for differences.

- We definitely need tests for this. You can probably create a test fixture with a package.json that installs a local tsconfig package with yarn.

- There seems to be more appropriate resolver APIs described here: https://yarnpkg.com/advanced/pnpapi#processversionspnp

**Comment by meriouma** [comment]
I'm not sure the issue with #9 was using `require.resolve`. `pnpapi.resolveRequest` has the same resolution logic and will resolve to `index.js` when passing a package name. I believe the issue is that instead of assuming the libraries are in `node_modules`, you should also use `require.resolve` or something similar to try and resolves the `package.json` and `tsconfig.json` first when the extends does not end with `.json`.

**Comment by JounQin** [comment]
If `extends: 'package-a'`, `tsconfig` field of `package-a/package.json` should be preferred instead of `main` field.

**Comment by JounQin** [comment]
Related ts source codes:

https://github.com/microsoft/TypeScript/blob/294a5a7d784a5a95a8048ee990400979a6bc3a1c/src/compiler/commandLineParser.ts#L2816

(I'm on a mobile, so cant search them very well.)

**Comment by meriouma** [comment]
Thanks @JounQin for the pointers. I'll take a look and reopen the PR once I can get it working cleanly.

**Comment by JounQin** [comment]
@meriouma See #28

**Comment by zkochan** [comment]
The fact that `require.resolve` is not used makes this library incompatible with pnpm's [globalVirtualStore](https://pnpm.io/settings#enableglobalvirtualstore).

**Pull request closed without merging**
